var entourageEpisodes = [
  'S1, E1 - Entourage', 'S1, E2 - The Review', 'S1, E3 - Talk Show', 'S1, E4 - Date Night', 'S1, E5 - The Script and the Sherpa', 'S1, E6 - Busey and the Beach', 'S1, E7 - The Scene', 'S1, E8 - New York', 'S2, E1 - The Boys are Back in Town', 'S2, E2 - My Maserati Does 185', 'S2, E3 - Aquamansion', 'S2, E4 - An Offer Refused', 'S2, E5 - Neighbors', 'S2, E6 - Chinatown', 'S2, E7 - The Sundance Kids', 'S2, E8 - Oh, Mandy', 'S2, E9 - I Love You, Too', 'S2, E10 - The Bat Mitzvah', 'S2, E11 - Blue Balls Lagoon', 'S2, E12 - Good Morning Saigon', 'S2, E13 - Exodus', 'S2, E14 - The Abyss', 'S3, E1 - Aquamom', 'S3, E2 - One Day in the Valley', 'S3, E3 - Dominated', 'S3, E4 - Guys and Doll', 'S3, E5 - Crash and Burn', 'S3, E6 - Three\'s Company', 'S3, E7 - Strange Days', 'S3, E8 - The Release', 'S3, E9 - Vegas Baby, Vegas!', 'S3, E10 - I Wanna be Sedated', 'S3, E11 - What About Bob?', 'S3, E12 - Sorry, Ari', 'S3, E13 - Less Than 30', 'S3, E14 - Dog Day Afternoon', 'S3, E15 - Manic Monday', 'S3, E16 - Gotcha!', 'S3, E17 - The Return of the King', 'S3, E18 - The Resurrection', 'S3, E19 - The Prince\'s Bride', 'S3, E20 - Adios Amigos', 'S4, E1 - Welcome to the Jungle', 'S4, E2 - The First Cut is the Deepest', 'S4, E3 - Malibooty', 'S4, E4 - Sorry, Harvey', 'S4, E5 - The Dream Team', 'S4, E6 - The WeHo Ho', 'S4, E7 - The Day Fuckers', 'S4, E8 - Gary\'s Desk', 'S4, E9 - The Young and the Stoned', 'S4, E10 - Snow Job', 'S4, E11 - No Cannes Do', 'S4, E12 - The Cannes Kids', 'S5, E1 - Fantasy Island', 'S5, E2 - Unlike a Virgin', 'S5, E3 - The All Out Fall Out', 'S5, E4 - Fire Sale', 'S5, E5 - Tree Trippers', 'S5, E6 - Redomption', 'S5, E7 - Gotta Look Up to Get Down', 'S5, E8 - First Class Jerk', 'S5, E9 - Pie', 'S5, E10 - Seth Green Day', 'S5, E11 - Play\'n with Fire', 'S5, E12 - Return to Queens Blvd', 'S6, E1 - Drive', 'S6, E2 - Amongst Friends', 'S6, E3 - One Car, Two Car, Red Car, Blue Car', 'S6, E4 - Running on E', 'S6, E5 - Fore', 'S6, E6 - Murphy\'s Lie', 'S6, E7 - No More Drama', 'S6, E8 - The Sorkin Notes', 'S6, E9 - Security Briefs', 'S6, E10 - Berried Alive', 'S6, E11 - Scared Straight', 'S6, E12 - Give a Little Bit', 'S7, E1 - Stunted', 'S7, E2 - Buzzed', 'S7, E3 - Dramedy', 'S7, E4 - Tequila Sunrise', 'S7, E5 - Bottoms Up', 'S7, E6 - Hair', 'S7, E7 - Tequila and Coke', 'S7, E8 - Sniff Sniff Gang Bang', 'S7, E9 - Porn Scenes from an Italian Restaurant', 'S7, E10 - Lose Yourself', 'S8, E1 - Home Sweet Home', 'S8, E2 - Out with a Bang', 'S8, E3 - One Last Shot', 'S8, E4 - Whiz Kid', 'S8, E5 - Motherfucker', 'S8, E6 - The Big Bang', 'S8, E7 - Second to Last', 'S8, E8 - The End'
]

// document.getElementById("generate").addEventListener("click", pickEpisode);
function pickEpisode(){
  var watchEpisode = entourageEpisodes[Math.floor(Math.random() * entourageEpisodes.length)];
  alert('You will watch ' +watchEpisode+ '');
  };
